require('plugins')
require('options')
require('maps')

require("plugins.treesitter")
require("plugins.lsp")
require("plugins.completions")
require('plugins.lualine')
require('plugins.telescope')
require('plugins.gitsigns')
require("plugins.transparent")
