#! /bin/sh

killall -q sxhkd
killall -q polybar
killall -q dunst
killall -q picom

while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done

sxhkd &
polybar top &
dunst -conf ~/.config/dunst/dunstrc &
nitrogen --restore &
picom -b
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DisplayPort-1 -d

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Alpenglow - Monokai
bspc config normal_border_color "#2E2E2E"
bspc config active_border_color "#2E2E2E"
bspc config focused_border_color "#666666"
bspc config presel_feedback_color "#666666"

# Dracula
# bspc config normal_border_color "#44475a"
# bspc config active_border_color "#44475a"
# bspc config focused_border_color "#6272a4"
# bspc config presel_feedback_color "#6272a4"

bspc config focus_follows_pointer true

bspc rule -a TablePlus desktop='^4' follow=on
bspc rule -a Thunderbird desktop='^5' follow=on
bspc rule -a Gimp desktop='^8' follow=on

bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Thunderbird:Msgcompose state=floating
bspc rule -a net-runelite-client-RuneLite state=floating
bspc rule -a Gpick state=floating focus=on
bspc rule -a Gufw.py state=floating focus=on center=on
bspc rule -a MEGAsync state=floating follow=on border=off layer=normal
bspc rule -a Nitrogen state=floating rectangle=800x500+0+0 center=on