#! /bin/sh

killall -q sxhkd
killall -q polybar
killall -q dunst

while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done

sxhkd &
polybar top &
dunst -conf ~/.config/dunst/dunstrc &

bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DisplayPort-1 -d

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Alpenglow - Monokai
bspc config focused_border_color "#999"

# Dracula
# bspc config normal_border_color "#44475a"
# bspc config active_border_color "#44475a"
# bspc config focused_border_color "#6272a4"
# bspc config presel_feedback_color "#6272a4"

bspc config focus_follows_pointer true

bspc rule -a TablePlus desktop='^4' follow=on
bspc rule -a Thunderbird desktop='^5' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a net-runelite-client-RuneLite state=floating
bspc rule -a Gpick state=floating focus=on

feh --bg-center ~/dotfiles/wallpapers/space-mountain.jpg