#! /bin/sh

killall -q sxhkd
killall -q polybar

while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

sxhkd &
polybar top &

bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DisplayPort-1 -d

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color    "#888888"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a net-runelite-client-RuneLite state=floating
bspc rule -a Gcolor3 state=floating focus=on

feh --bg-center ~/Pictures/Wallpapers/neon.png